.TH   "FACTER" "8" "September 2012" "Puppet Labs, Inc" "Facter manual"
.SH NAME
Facter - Collect and display facts about the system.
.
.SH SYNOPSIS
.sp
Collect and display facts about the system.
.SH USAGE
.INDENT 0.0
.INDENT 3.5
facter [\-d|\-\-debug] [\-h|\-\-help] [\-p|\-\-puppet] [\-v|\-\-version] [\-y|\-\-yaml] [\-j|\-\-json] [fact] [fact] [...]
.UNINDENT
.UNINDENT
.SH DESCRIPTION
.sp
Collect and display facts about the current system. The library behind
Facter is easy to expand, making Facter an easy way to collect
information about a system from within the shell or within Ruby.
.sp
If no facts are specifically asked for, then all facts will be returned.
.SH OPTIONS
.sp
yaml:    Emit facts in YAML format.
.sp
json:    Emit facts in JSON format.
.sp
puppet:  Load the Puppet libraries, thus allowing Facter to load Puppet specific (custom) facts
.sp
version: Print the version and exit.
.sp
help:    Print this help message.
.sp
debug:   Enable debugging.
.sp
trace:   Enable backtraces.
.sp
timing:  Enable timing.
.SH EXAMPLE
.INDENT 0.0
.INDENT 3.5
facter kernel
.UNINDENT
.UNINDENT
.SH AUTHOR
.sp
Luke Kanies
.SH COPYRIGHT
.sp
Copyright (c) 2012 Puppet Labs, Inc Licensed under the Apache 2.0
license
.
