source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem "beaker", "~> 2.23"
gem 'rake', "~> 10.1.0"
gem "multi_json", "~> 1.8"

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
