---
HOSTS:
  master:
    roles:
    - master
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
  agent:
    roles:
    - agent
    platform: osx-yosemite-x86_64
    hypervisor: vcloud
    template: osx-1010-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
