---
HOSTS:
  agent-10-x86_64-rubyx86:
    roles:
    - agent
    platform: windows-10-64
    ruby_arch: x86
    hypervisor: vcloud
    template: win-10-ent-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
