source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :development, :test do
    gem 'rake'
    gem 'rspec'
    gem 'mocha'
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
