source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem 'ffi', '~> 1.9.6', :require => false
gem 'cfacter', :path => File.expand_path("..", __FILE__), :require => false

group :development, :test do
    gem 'rake', "~> 10.1.0"
    gem 'rspec', "~> 2.11.0"
    gem 'mocha', "~> 0.10.5"
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
