# frozen_string_literal: true

require_relative 'legacy_facter'
require_relative '../util/fact'
require_relative '../util/collection'
require_relative '../util/fact'
require_relative '../util/loader'
require_relative 'execution/base'
require_relative 'execution/windows'
require_relative 'execution/posix'
require_relative '../util/values'
require_relative '../util/confine'

require_relative '../util/config'

require_relative '../util/normalization'
require_relative 'execution'
require_relative 'resolvable'
require_relative 'suitable'
require_relative '../util/resolution'
require_relative 'directed_graph'
require_relative 'resolvable'
require_relative 'aggregate'
require_relative '../util/composite_loader'
require_relative '../util/parser'
require_relative '../util/directory_loader'
require_relative '../util/nothing_loader'
require_relative '../util/nothing_loader'
